### ISSUE TITLE
Add a way to list the polls created by a user

### ISSUE THREAD

**Issue by mudlock** [electology/approval_frame#14]

**Comment by Brianjr0428** [comment]
@ashimaathri 
For now my thought is to make user go to their own page listing polls they create.
For this issue, I will just have the page along with options (remove, suspend, edit options etc.) but they are not clickable at this moment since I think we can leave this part to #15.
What do you think?

**Comment by ashimaathri** [comment]
@Brianjr0428 That sounds good.

**Comment by Brianjr0428** [comment]
@ashimaathri 
I have sent PR two days ago.
Let me know if you couldn't see it or if you have any comment.
Thanks!

**Comment by ashimaathri** [comment]
@Brianjr0428 Thanks for the PR. I did look at it, but I haven't had time to go through it thoroughly. Will let you know soon.

**Comment by Brianjr0428** [comment]
@ashimaathri 
No problem.
Please take your time!
