### ISSUE TITLE
Login should accept both email ID or username

### ISSUE THREAD

**Issue by ashimaathri** [electology/approval_frame#32]

**Comment by rupalkhilari** [comment]
It seems that currently multiple usernames can be associated with the same Email ID. To have the login accept either email ID or username, should we only allow one username per Email ID ? 

Thanks,
Rupal

**Comment by ashimaathri** [comment]
I vote we remove the user ID property altogether and keep only the email as the unique ID for a user. There may be a way to do that in the registration-redux module, we need to dig in the documentation to find out.

**Comment by rupalkhilari** [comment]
The user ID does seem redundant if we need to keep both user ID and Email ID unique.  (http://stackoverflow.com/questions/2131533/django-registration-force-unique-e-mail outlines a way to have both unique fields). 
But in case the user ID property is removed, it may impact https://github.com/electology/approval_frame/issues/13 . I think it may not be appropriate to display the person's email ID (or a part of it) against a poll question due to privacy reasons. 
Please let me know your thoughts. 

Thanks,
Rupal

**Comment by ashimaathri** [comment]
@rupalkhilari That is a good point. We still need the username for display purposes and cannot use the email ID due to privacy reasons. We can go with the way you have outlined to make both of them unique and ask the user to enter either during login.  
This can be made clearer to the user by using the text 'Enter your email ID or username' as a placeholder/label for the login input box.

**Comment by ashimaathri** [comment]
@rupalkhilari I've made the changes to ensure that the email is unique in #50.

**Comment by rupalkhilari** [comment]
Thanks @ashimaathri ensuring that the email is unique. I have added a custom backend to approval_frame/backends.py - not sure if the class should be packaged elsewhere. Please let me know in case of any comments.
