### ISSUE TITLE
Have opt-in feature for monthly newsletter when signing up

### ISSUE THREAD

**Issue by ashimaathri** [electology/approval_frame#33]

**Comment by adihemdev** [comment]
Ashima,

Could this be implemented using JavaScript? Also what will happen once the user opts for the monthly newsletter? Will he receive an email confirmation?

**Comment by ashimaathri** [comment]
@adihemdev this would involve

1. HTML for the checkbox and the corresponding text that says 'Sign up for the newsletter'
2. Server side logic for checking if this checkbox was checked by the user when submitting the form and if so, adding the corresponding information to the database along with other attributes of the user such as username, email address, hashed password etc.
3. As the user already receives an activation email on signup, we can piggy-back on that for user confirmation of signup.
4. Some way to connect the program that sends the newsletter to our database of users that have signed up for it. For now, we can do it manually through the administration console.

I don't see the need for using JavaScript at this stage.

**Comment by Daniel-Avila** [comment]
@ashimaathri I can do this one and get it checked in. 

Have you had time to do a code review on my pull request?

**Comment by kushankr** [comment]
@rupalkhilari 

Hi Rupal,
Aaron mentioned this as a priority item in his email. This issue was last updated in Aug, 2015. Is it ok if i try this one out?

**Comment by rupalkhilari** [comment]
Sure Kushank, please feel free to take this up if you have time. 
Thanks a lot !

**Comment by kushankr** [comment]
Thanks, Rupal.

**Comment by kushankr** [comment]
Rupal, I have a question. I saw that CES sends a newsletter to subscribers and I saw the subscribe link in Aaron's mail. If you have knowledge about this, can you please tell me where is this newsletter stored and how can we use this in this issue? Thanks, Rupal.

**Comment by rupalkhilari** [comment]
Hi Kushank, 
Aaron had mentioned in his email that their newsletter system uses [MailChimp](http://mailchimp.com/) and had given the API key that we could use for this. 
I think we could use the official Python/Django API for mailchimp as given in https://pypi.python.org/pypi/mailchimp. This page also lists  a Django example to display the existing lists to add a member as a subscriber to that list - https://github.com/mailchimp/mcapi2-python-examples. On editing the mcapi_python_example/utils.py to use the given API key perhaps we could use the [subscribe()](https://github.com/mailchimp/mcapi2-python-examples/blob/master/django/lists/views.py#L36).

**Comment by rupalkhilari** [comment]
I think the API key could be read from a variable in local_settings.py, so perhaps this feature does not need to be workable for those without the API key during development.

**Comment by kushankr** [comment]
Thanks a lot, Rupal!

**Comment by kushankr** [comment]
Hi Rupal,

I have been researching this issue: I have learned that ZIP CODE field is required (in addition to email) on user subscription. So if we give the user a checkbox to subscribe to newsletter on signing up, in the registration page - a zip code field has to be added. Without it, the 'subscribe' function returns an error. I have verified this in multiple places - current newsletter form (link is usually present in Aaron's email) as well as getting what are the required fields through code/API.

There is a way out of this. I can make the zip code field optional through code. But this will impact the existing newsletter application - I am sure Aaron made the decision to make zip code a required field due to some reason because I am seeing that some demographic data is being collected. 

But I was also thinking: Is it really a good idea to put a zip code field in an online registration form? I was thinking that if the user clicks on newsletter checkbox, we can enable or disable the zip code field. What do you think about this, Rupal? I would appreciate your thoughts on this. Thanks.

**Comment by rupalkhilari** [comment]
@kushankr , I see, I like your suggestion of having the zip code field enabled and requested from the user only when the newsletter checkbox is checked. That way we could keep it consistent with the existing behavior of signing up for the newsletter. As you mentioned, i too think this data should be mandatory since it might be used somewhere.

**Comment by kushankr** [comment]
Thank you for your reply, Rupal. I will go ahead and implement this.

**Comment by kushankr** [comment]
Hi Rupal, I am still working on this. Thank you for updating Aaron. I hope to finish this soon.

**Comment by kushankr** [comment]
@rupalkhilari 

I have a question about this: So when you subscribe to newsletter, a confirmation mail is sent. Clicking on 'Register' also sends a confirmation mail. In our functionality, should there be two confirmation mails sent - one for activating account and one for subscribing to newsletter? or should we use activating account email on register to confirm subscription to newsletter as well?

**Comment by rupalkhilari** [comment]
Thats a good question, Kushank. I would think it should use a single email for both registration and newsletter, since the purpose for both is mainly to confirm if the email address is valid. If it is not very straightforward to have, perhaps we could start with two emails and then later have it send only one. What do you think ?

**Comment by kushankr** [comment]
Hi Rupal, Thank you for your reply. I am hoping that I would be able to code it to use a single email for both registration and newsletter. But depending on what I encounter, I will see if it is more straightforward to have two emails for now - and later merge it in one. I will keep you posted. Thanks, Rupal.

**Comment by kushankr** [comment]
Initiated a PR

#103 

Can you please review it, Rupal? Thanks.

**Comment by rupalkhilari** [comment]
Thanks Kushank ! Closing this. #103
