### ISSUE TITLE
 I-frame should automatically adjust height and width according to number of options.

### ISSUE THREAD

**Issue by ashimaathri** [electology/approval_frame#34]

**Comment by rupalkhilari** [comment]
Hi, 

I have implemented this using Javascript in the pull request https://github.com/electology/approval_frame/pull/44 . This adds an iframe Preview to the page, and calculates the appropriate height for the iframe based on that. The width of the iframe however is kept constant at 350px (max-width of the content's body) since displaying the footer always seems to require it. 

I had considered counting the number of choices to make an estimate, or maybe using Ghost - but both seemed unreliable without having the page rendered. 

This option with Javascript should scale irrespective of the CSS etc with slight variation in different browsers. 
Please let me know if you think this is an acceptable way to go about this. 


Thank you,
Rupal
