### ISSUE TITLE
Add ability for users to manage polls: edit poll 

### ISSUE THREAD

**Issue by Brianjr0428** [electology/approval_frame#66]

**Comment by Daniel-Avila** [comment]
and I will take this one also.

**Comment by Daniel-Avila** [comment]
Ok submitted a pull request for this one. Im sure you will let me know when it gets merged or if you need to kick it back to me.

**Comment by ashimaathri** [comment]
Thanks @Daniel-Avila! I see that you're still working on it. I'll look at it as soon as possible (probably after Thursday this week).

**Comment by rupalkhilari** [comment]
We might need to revisit this. We should probably see which bits of it can be reused from https://github.com/electology/approval_frame/pull/71 . I also think we should perhaps split this ticket into multiple tickets based on each section of the poll and the poll settings panel - so that we can carefully evaluate upto what extent each part can be edited and make it more manageable. 

1) Edit poll question and choices.
2) Edit poll voting ability (anyone, logged in, email) 
3) Edit poll close date and times and display/countdown.
4) Edit write-in option/leading color option.

I shall go ahead unless anyone raises any concerns.

**Comment by rupalkhilari** [comment]
Have raised #108, #109, #110, #111 for this. We could close this ticket once these have been addressed.

**Comment by rupalkhilari** [comment]
Closing this as all related tickets have been addressed. 
Thanks to all volunteers who have contributed to this!
