### ISSUE TITLE
Add ability for users to manage polls: suspend poll

### ISSUE THREAD

**Issue by Brianjr0428** [electology/approval_frame#67]

**Comment by Daniel-Avila** [comment]
I can take this one.

**Comment by Daniel-Avila** [comment]
What exactly do we mean by "suspend" a poll? What if the poll gets unsuspended after the poll's close_date (which is a new thing so we might have to chat about it.)

**Comment by ashimaathri** [comment]
Hmm. I hadn't thought of that. Maybe we could prompt for a new date in such a case? What do you think?

**Comment by Daniel-Avila** [comment]
If prompting is what you want. Then prompting is what you shall have! :)

So how about this: 
* When a poll gets "unsuspended":
    * The user is redirected to the Edit Poll page with the poll data in place in the form.
    * If there are any issues we can load helpful messages into the PollUpdateForm's  non_field_errors which are displayed in the form if they exist. 
* Possible issues:
    * The poll's close date is in the past. Please edit it.
    *The poll has no Choices. Please add some.

Is there anything else you can think of?

**Comment by Daniel-Avila** [comment]
Another option would be to calculate the time delta from the original open and close dates and reset the close date from "now" + calculated_time_delta. IIF the close date is in the future. 

As always the poll's owner will always have the option to edit.

**Comment by Daniel-Avila** [comment]
Ok so this one is done and in the pull request. Play with it and see what you think.

Lets find something else to work on now.

**Comment by rupalkhilari** [comment]
I think the 'suspend' should be a part of the edit functionality. Since we are dealing with poll close dates and times there, i feel that suspending a poll is also a form of editing it.

**Comment by balajisubr** [comment]
@rupalkhilari Is this being worked on?

**Comment by rupalkhilari** [comment]
@balajisubr , I don't think this PR was updated according to the review comments and had to be closed as it was too out-of-date with the codebase. 
We need to figure out the definition of suspend in this case. According to what I think, for now, the poll will simply not allow any votes on it (Vote button will be disabled with an appropriate message like 'Sorry, the poll has been temporarily suspended.'). 
What do you think ?

**Comment by balajisubr** [comment]
@rupalkhilari  
Should suspended polls even be shown to users? 
If a user goes to a suspended poll, they can be shown a message like above "Sorry, the poll has been temporarily suspended" but do we want to display the poll choices?
If a poll is currently suspended, should the poll index page show a "Unsuspend" or "Reactivate" button in place of the "suspend" button?
Should there be a JS Dialog which asks for user confirmation about suspending a poll and gives info about what would happen to the poll if the user clicks on Suspend ?

**Comment by rupalkhilari** [comment]
Those are good questions. I think we should allow suspended polls to be shown on the main page. That way we can avoid confusion between the 'Show poll on home page' option and this. 

I think 'Unsuspend' seems good for now, also having a visual representation - perhaps having the cell in a darker grey would distinguish it nicely from the other polls. 
Also maybe not now, but we should also look at changing the layout of the 3 buttons on the cell (perhaps adding icon buttons instead of text with a tooltip). Something like what Github comments do too, I could raise a ticket for that. 
<img width="220" alt="screen shot 2017-07-28 at 8 16 41 am" src="https://user-images.githubusercontent.com/7693347/28723954-4b305c86-736d-11e7-8e72-4f177285126e.png">


There should be a JS Dialog box that confirms with the user and explains the implications of suspending the poll.

**Comment by balajisubr** [comment]
@rupalkhilari As pointed out by @Daniel-Avila earlier, should the poll unsuspend  be allowed for a suspended poll if the current time is after the poll close date?

**Comment by rupalkhilari** [comment]
@balajisubr , I think your current implementation looks good where we keep both the behaviors independent of each other.
