### ISSUE TITLE
Allow user to copy html embed code

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#80]
In the embed_instructions.html page, provide a 'Copy text' button to facilitate easy copying of the html snippet to clipboard.

**Comment by kushankr** [comment]
Working on this!

**Comment by kushankr** [comment]
Hi Rupal,

I have coded for this and I thought that I will ask you for your thoughts.
I have attached the screenshots.
![issue 80 - 1](https://cloud.githubusercontent.com/assets/8802245/11755731/5a0da86e-a022-11e5-9b44-abdf9861ddcf.JPG)
![issue 80 - 2](https://cloud.githubusercontent.com/assets/8802245/11755733/5dcdbe9e-a022-11e5-8c41-f9552d137d7d.JPG)
![issue 80 - 3](https://cloud.githubusercontent.com/assets/8802245/11755734/6047d0e2-a022-11e5-865f-142cdedc32a5.JPG)

I have used 'bootstrap'  (which is already used in the app) for styling. The thing is that the green button was not looking as good as i thought it would. Also, I placed the button on top of textarea where iframe url is shown because it looked better this way (similar to how "Write" button looks on top of this github box when you write).  Also, I am showing messages below the box as a way to tell the user that he/she has succeeded or may be not - if not, the text is already selected and all the user needs to do is press Ctrl +C (This might never happen, I deliberately induced error in the code to show this error message so that you can see it.) 

And I did test the code. When you press 'Copy' button, the text is copied and if you press Ctrl+V or paste, the HTML Code Snippet is pasted.

However, I can change the layout and the functionality based on your feedback.  Please feel free to suggest any changes. Thanks, Rupal.

**Comment by rupalkhilari** [comment]
Hi Kushank, 

Thanks for looking into this ! The changes look really good. Though I would think that the 'Copy to Clipboard' button should be aligned to the top right of the textarea box, above it (as it is done [here](http://s3.amazonaws.com/screensteps_live/images/hubspot/142684/1/rendered/9790afa3-ad2d-4f58-9c4b-be924587af2c.png)) or below the textarea box (as [here](http://twitterbootstrapbuttons.w3masters.nl/)).  The reason for this is that I believe that probably the iframe code should immediately follow the 'Put this code in your site:'. Right now the button seems to be coming in between both of these. Let me know if you think otherwise or have any concerns. 
The success/failure message looks great as it is. 

Thanks!

**Comment by kushankr** [comment]
Thank you, Rupal for your feedback. I will work on aligning the 'Copy to Clipboard' button.

**Comment by kushankr** [comment]
[PR#84](https://github.com/electology/approval_frame/pull/84)

I have incorporated the feedback you provided, Rupal.
Please review the PR, Rupal

Thank you, Rupal.

**Comment by rupalkhilari** [comment]
Thanks, Kushank. It looks great now, closing this.
