### ISSUE TITLE
Add a free/libre/open license!!

### ISSUE THREAD

**Issue by wolftune** [electology/approval_frame#87]
This code is all-rights-reserved by legal default until you add a license. Furthermore, you have to handle all sorts of challenges when accepting code from others if the licensing isn't clear. If you have a LICENSE file here, then others who adjust the code in a repository that has the same file can at least be assumed to stick to the same license.

I would consider GNU AGPLv3+ (+ means include the "or later" clause) as the most community-centered freedom-respecting license. The only concern is that if you want to push adoption of this software by other websites which may be proprietary and where they would integrate this into their site, then you may want a more permissive license. GPLv3+ would be fine because it would be equally usable for even proprietary sites and the copyleft (i.e. share-alike / pass-on-the-freedoms) effect would only take place if someone distributes the code and not when they just use it on a site. You could slightly improve license-compatibility with GPLv2+ but that would lose the patent clauses and such. Otherwise, Apache v2 would be a decent option, or MIT to be most permissive. While I'd probably go with AGPLv3+ or maybe GPLv3+, *any* of these would be better than the really unacceptable state of having no license.

**Comment by will-martin** [comment]
afuerro is the most onerouse GPL and forces all deployments to expose their codebase: a major security hole in election oriented work.

**Comment by wolftune** [comment]
"expose their codebase" is arguably *healthy* for security by some arguments, but I see the point. So, don't go with Affero then.

**Comment by rupalkhilari** [comment]
@wolftune , thanks for raising this issue. We hadn't yet started considering the license part of this yet since the project is in its alpha stage. [This link](http://choosealicense.com/licenses/) was pretty useful for me to understand the finer points of the licenses you mentioned. GNU GPLv3+ does seem pretty favorable, probably something we could discuss with Aaron as well ?

**Comment by wolftune** [comment]
@rupalkhilari I hesitated to post that link because even though it is generally accurate, it's carefully structured to just slightly downplay GNU licenses (within the range of plausible deniability) because the GitHub folks behind it have a conflict-of-interest wanting to promote permissive licenses that can then be co-opted into proprietary stuff because GitHub's income comes from offering private (usually proprietary) repos and such. I will still agree that it's an okay way to review some of the distinctions. See https://snowdrift.coop/p/snowdrift/w/en/licenses for another perspective on the whole topic.

**Comment by rupalkhilari** [comment]
I see, thanks for the link. It was very informative! @AaronHamlin suggested that we go ahead with the GNU GPLv3 license for now, and we could change it later if necessary. I have added the LICENSE file, though have not yet modified every source code file to put in the copyright notice (as mentioned in the license) . I was wondering if there are any other distinctions - this being an open source project for a non profit organization vs being owned by an individual.

**Comment by wolftune** [comment]
FWIW, lots of these git repos don't need the per-file stuff as much since Git kinda manages the whole thing, and just a top-level LICENSE file is adequate

**Comment by lpsmith** [comment]
Changing the license later isn't necessarily so simple.   Unless a contributor is an _employee_ of the Center for Election Science,  _or_ have signed a written statement of copyright assignment (copyright assignment cannot be a verbal agreement),  the current owners of the copyright on this software is the seven contributors.    These contributors own the copyright on their respective contributions,  and ultimately have control over how their contributions are licensed.

(Incidentally, the copyright notice at the beginning of the GPL only applies to the text of the license itself,  which is the intellectual property of the Free Software Foundation.   It does not apply to the software,  which is not property of the FSF.)

So to resolve the immediate issue,  I think it's probably appropriate to pick a open source license,  and make it clear to the current contributors that we've picked a license.    If none of the current contributors object within a reasonable period of time,  then it should be quite safe to say that everybody has acquiesced to licensing their contributions under the chosen license,  especially considering that everybody who has been involved expected this to be an open source effort.  

However,  changing the license down the road is considerably more tricky.    Moving from the copylefted GPLv3 to a more permissive license such as Apache2,  means that we would need to obtain permission from all of the copyright holders (i.e. the contributors),  or remove their contributions if they don't agree and we really do want to make the switch.    Because there wasn't a clear expectation that the license could change,   and since this occurence may happen some time down the road and may also involve new contributors who got involved with the expectation of GPL licensing,  we really shouldn't rely on acquiescence for a move from GPL to Apache.

On the other hand, moving from a Apache2 to GPLv3 wouldn't necessarily require the consent of the contributors,  but it could be quite difficult for such a move to have much significance in practice.    Assuming the old contributions remain Apache2 licensed,  which may certainly be incorporated into a GPLv3-licensed work,  all that would be required for somebody who wishes to treat the work as Apache2 is to remove the newer,  GPLv3-licensed contributions.     And if we obtained consent from all of the contributors to switch everything over to GPLv3 and to stop offering the software as Apache2,  then anybody who has obtained a copy of the software under the Apache license could fork the software and begin offering it under the Apache license again.

So if anything,  starting out with the GPL or AGPL with the possibility of moving to Apache makes somewhat more sense,  but actually making that move may be difficult.

**Comment by wolftune** [comment]
While everything @lpsmith said is accurate, I should add some points:

GPLv3 is easily one-direction compatible with AGPLv3, so that change is easier. Also, while a CLA can seem nice, it's somewhat of a trust issue. Some contributors will feel less comfortable with a CLA. The thing that best assures stability in the commons is when something is copyleft (like GPL, ideally AGPL, although issues with it are acknowledged) and does *not* have a CLA, and thus the dificulty of license change is a *feature*. In the core sense, from a *democratic* viewpoint, license change to another more permissive without a CLA requires a consensus. So a CLA is anti-democratic, giving one entity authority to unilaterally change the license. So again, the thing that ensures everyone democratic say about this is the combination of copyleft and *no* CLA.

Also, it's relatively easy to make a license change despite the issues if it's easy to reach everyone involved and easy to show everyone that the license change is good for the project.

**Comment by lpsmith** [comment]
Well, a Contributor License Agreement doesn't necessarily imply copyright assignment,  though it often does.    It's not a terrible idea to obtain CLAs from everybody to clarify that the contributors retain the copyright and that they offer the software under whichever license the project is using.

**Comment by wolftune** [comment]
CLA does not imply copyright assignment, but it tells people that they will *not* need to be consulted (i.e. they will have no vote in consenting!) on the license change for the project, regardless of having copyright on their own work still. That's why some contributors distrust CLAs, it looks like a thing projects can use to unilaterally go proprietary or something later.

Dani Ariely says, "It is easier to avoid temptation than to resist it". Lack of CLA means the project leaders are refusing to even *claim* the power to do whatever with the license without consent, so there's no temptation for them to abuse that power if they don't have it.

**Comment by rupalkhilari** [comment]
Thanks for sharing your knowledge of the finer points of license change. We probably will not be changing the GNU GPLv3 in the immediate future. So for now, I shall close this one since the license file has been added to the project. 
Thanks!

**Comment by lpsmith** [comment]
There is a similar sort of asymmetry between the AGPL and GPL as there is between the GPL and Apache:    moving from AGPL to GPL would require consent of the copyright holders,  whereas moving from GPL to AGPL could be difficult to make stick.

As for my personal opinion on licensing for this project,  it depends a bit on what this project is really trying to accomplish.   As I understand Aaron Hamlin's original vision,  it was a purely informal web polling software with minimal barriers to ballot-stuffing that supported approval voting.    Though I have not followed development on this project closely,  it seems to be moving considerably towards formal voting software.     And,  I've thought about these two problems a fair bit,  and to do a good job with either one requires some rather different implementation decisions,  without a whole lot of overlap between the two.

My point is this:  I'd probably license formal voting software under the AGPL,  while informal polling software needs the ability to integrate secret algorithms to attempt to ameliorate ballot stuffing,  so pure AGPL wouldn't be entirely appropriate (in my opinion).

You may want to read up on the "application service provider GPL loophole" to understand the AGPL and why it was created.   The wikipedia page on the [AGPL](https://en.wikipedia.org/wiki/Affero_General_Public_License) is not a terrible starting point.

If the GPL really is your final decision for now (and keep in mind this could be difficult or practically impossible to change later),  that's fine too.

**Comment by lpsmith** [comment]
@rupalkhilari
@ashimaathri
@kushankr
@mudlock
@Brianjr0428
@NigelKibodeaux
@kyleneideck

This is your notice to you,  the copyright holders of the Center for Election Science's "Approval Frame" software project,  that the project is assuming that you have provided your contributions under the GNU General Public License version 3, or later.

**Comment by kyleneideck** [comment]
Fine by me 👍🏼

**Comment by rupalkhilari** [comment]
@lpsmith, I too agree to provide my contributions under GNU GPLv3. Thanks for the insights on this matter. I understand your point about the ASP loophole in the GNU GPLv3 with web application usage vs distribution. As far as I understand, [AGPL](http://www.gnu.org/licenses/why-affero-gpl.en.html) is more permissive than GPLv3. As you mentioned, it purely depends on the vision of the software that CES and Aaron have for it. But as a volunteer, I would have no issue contributing to it with either license.

**Comment by kushankr** [comment]
I agree to provide my contributions under GNU GPLv3+

**Comment by wolftune** [comment]
@rupalkhilari to clarify, **L**GPL is more permissive. **A**GPL is a *stronger* copyleft which states that the copyleft terms apply even if "conveying" the software is done by giving others access over a server (whereas regular GPL's copyleft only applies if you send someone software for them to run on their own machine)
